image: node:15.6-buster

stages:
  - unit-tests
  - e2e-tests

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn install --cache-folder .yarn

unit-tests:
  stage: unit-tests
  script:
    - yarn test:unit --coverage --ci
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 hour

e2e-tests:
  stage: e2e-tests
  services:
    - name: selenium/standalone-chrome
      alias: chrome
  script:
    - yarn test:e2e
