image: node:15.6-buster

stages:
  - unit-tests
  - e2e-tests

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn install --cache-folder .yarn

unit-tests:
  stage: unit-tests
  script:
    - yarn test:unit --coverage --ci
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 hour

e2e-tests:
  stage: e2e-tests
  services:
    - name: selenium/standalone-chrome
      alias: chrome
  before_script:
    - apt-get update
    # Install Chrome
    - apt-get install -yq libnss3 unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - apt install -y ./google-chrome-stable_current_amd64.deb
    # Install Firefox
    - apt-get install -y firefox-esr
  script:
    - yarn test:e2e
